[windows]
win-app-01 ansible_host=10.10.10.11
win-db-01 ansible_host=10.10.10.12

[unix]
lin-app-01 ansible_host=10.20.10.11
lin-db-01 ansible_host=10.20.10.12

[all:vars]
ansible_python_interpreter=/usr/bin/python3
